### ISSUE TITLE
如果设计稿不是1920的话，转换rem错误

### ISSUE THREAD

**Issue by GreatAuk** [QuellingBlade/postcss-px-to-rem#1]
![image](https://user-images.githubusercontent.com/20253809/64595634-efc24000-d3e4-11e9-8687-9fe5c35d2825.png)
![image](https://user-images.githubusercontent.com/20253809/64595891-71b26900-d3e5-11e9-94d1-0a5c0a0c4f23.png)

**Comment by njleonzhang** [comment]
```
{
  unitToConvert: 'px',
  widthOfDesignLayout: 1920,
  unitPrecision: 5,
  selectorBlackList: [],
  minPixelValue: 1,
  mediaQuery: false
};
```

用 `widthOfDesignLayout` 试试？

**Comment by GreatAuk** [comment]
@njleonzhang ~~一样的情况哟~~。sorry,可以了。刚才改错地方了。上面的错误代码是直接从[demo](https://www.njleonzhang.com/flexible-pc-full-screen/)拷的

**Comment by GreatAuk** [comment]
你这个方案和常见的移动端适配有区别吗，感觉都是body设置一个fontSize。然后就是使用px-to-rem插件转换了。（sorry,看了你写的博客，但是没怎么看懂。所以想问下）

**Comment by njleonzhang** [comment]
@GreatAuk  额，差不多吧，具体细节就是博客里写的那样了啊。
